% The reference can be found here http://math.bu.edu/people/mveillet/html/alphastablepub.html
x = -5:.01:5;
beta = 0.0;
gam = 1;
delta = 0;
plot( x , stblpdf(x,.5,beta,gam,delta,'quick'),...
  x , stblpdf(x,.75,beta,gam,delta,'quick'),...
  x , stblpdf(x,1,beta,gam,delta,'quick'),...
  x , stblpdf(x,1.25,beta,gam,delta,'quick'),...
  x , stblpdf(x,1.5,beta,gam,delta,'quick') )
axis([-5 5 0 .7]);
title('Symmetric \alpha-stable densities, \beta = 0, \gamma = 1, \delta = 0');
legend('\alpha = 0.5',...
    '\alpha = 0.75',...
    '\alpha = 1.0',...
    '\alpha = 1.25',...
    '\alpha = 1.5' )